### ISSUE TITLE
invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by voxik** [intridea/multi_json#104]
Hi,

Running test suite as `LANG=C rspec spec` causes error

```
  1) MultiJson ok_json behaves like an adapter .dump allows to dump JSON with UTF-8 characters
     Failure/Error: expect(MultiJson.dump({'color' => 'żółć'})).to eq('{"color":"żółć"}')
     ArgumentError:
       invalid byte sequence in US-ASCII
     Shared Example Group: "an adapter" called from ./spec/multi_json_spec.rb:157
     # /usr/share/gems/gems/rspec-expectations-2.12.1/lib/rspec/expectations/fail_with.rb:47:in `block in any_multiline_strings?'
     # /usr/share/gems/gems/rspec-expectations-2.12.1/lib/rspec/expectations/fail_with.rb:47:in `each'
     # /usr/share/gems/gems/rspec-expectations-2.12.1/lib/rspec/expectations/fail_with.rb:47:in `any?'
     # /usr/share/gems/gems/rspec-expectations-2.12.1/lib/rspec/expectations/fail_with.rb:47:in `any_multiline_strings?'
     # /usr/share/gems/gems/rspec-expectations-2.12.1/lib/rspec/expectations/fail_with.rb:24:in `fail_with'
     # /usr/share/gems/gems/rspec-expectations-2.12.1/lib/rspec/expectations/handler.rb:31:in `handle_matcher'
     # /usr/share/gems/gems/rspec-expectations-2.12.1/lib/rspec/expectations/expectation_target.rb:34:in `to'
     # /builddir/build/BUILD/rubygem-multi_json-1.7.1/usr/share/gems/gems/multi_json-1.7.1/spec/adapter_shared_example.rb:126:in `block (3 levels) in <top (required)>'
```

`LANG=en_US.utf8 rspec spec` runs just perfect. I suspect that it is some issue with embedded ok_json.
